### ISSUE TITLE
Hot Module Reloading tries to create another element

### ISSUE THREAD

**Issue by jamestowers** [fromAtoB/vue-stripe-elements#15]
When using hot module reloading, vue-stripe-elements tries to create another StripeElelment on the page when you make a change:

```
[Vue warn]: Error in beforeMount hook: "IntegrationError: Can only create one Element of type card."

found in

---> <StripeElement>
       <Card>
            ...
```

Which is then followed by:
```
[Vue warn]: Error in mounted hook: "TypeError: this._element is undefined"
```

and the element is removed from the page.

**Comment by nkoehring** [comment]
@jamestowers the current version fixes that

**Comment by softbeehive** [comment]
@jamestowers, it should be fixed since `v0.2.4`.

**Comment by cmann50** [comment]
I am also getting this same error today.  I downgraded from 0.2.9 to _"vue-stripe-elements-plus": "^0.2.8"_ in package.json, ran npm install, and it works fine.

**Comment by vladislavkoz** [comment]
You can add refs("SomeRef") to you component and then call in some function(like beforeDestroy() or some else) this.$refs.SomeRef.$destroy(). Profit)

**Comment by matthewhardern** [comment]
This is still broken, HMR using parcel JS this still happens

**Comment by manniL** [comment]
I'm experiencing the issue as well.

**Comment by perle-rare** [comment]
me too , using the version `"vue-stripe-elements-plus": "^0.3.0",`

**Comment by fsproru** [comment]
Having the same issue with version `0.3.2`, looks like it also outputs some hardcoded path below:

```
[Vue warn]: Error in beforeMount hook: "IntegrationError: Can only create one Element of type card."

found in

---> <StripeElement> at /Users/jirikratochvil/Work/fromatob/oos/vue-stripe-elements/src/StripeElement.vue
       <Card> at /Users/jirikratochvil/Work/fromatob/oos/vue-stripe-elements/src/Card.vue
```

**Comment by sebastienfilion** [comment]
For anyone still experiencing this issue; it's probably caused by something like Vue Router; 
before the previous page is destroyed, the current page must be created, to allow for a smooth transition.
My solution was to have a boolean that is set to `true` only when the current page is mounted; then I use `v-if` on the `stripe-element` or the appropriate parent... This ensures that when a new Stripe component is created, the previous one has been correctly destroyed.
Hope it helps someone...

```
data: {
  ...
  mountStripeElement: false,
  ...
},
mounted() {
  this.mountStripeElement = true;
}
```

**Comment by perle-rare** [comment]
@sebastienfilion you saved my day. 
that solved my issue 
Many thanks

**Comment by Sergey98Am** [comment]
> For anyone still experiencing this issue; it's probably caused by something like Vue Router;
> before the previous page is destroyed, the current page must be created, to allow for a smooth transition.
> My solution was to have a boolean that is set to `true` only when the current page is mounted; then I use `v-if="mountStripeElement "` on the `stripe-element` or the appropriate parent... This ensures that when a new Stripe component is created, the previous one has been correctly destroyed.
> Hope it helps someone...
> 
> ```
> data: {
>   ...
>   mountStripeElement: false,
>   ...
> },
> mounted() {
>   this.mountStripeElement = true;
> }
> ```

Thank You so much

**Comment by Sergey98Am** [comment]
@sebastienfilion Thank you so much
